line-length = 120
target-version = "py311"
[lint]
# Enable: eror check, import order
select = ["E", "F", "I"]
ignore = ["D400"]
[format]
# Format docstrings
docstring-code-format = true
quote-style = "double"
indent-style = "space"
line-ending = "auto"