[project]
name = "deeprag-ext"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[dependency-groups]
es = [
    "elasticsearch[async]>=8.11.0",
    "langchain-elasticsearch>=0.0.3",
]
neo4j = [
    "neo4j>=5.16.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
