# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import chat_pb2 as chat__pb2
from . import rag_pb2 as rag__pb2


class RAGServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieval = channel.unary_unary(
                '/raghub_interfaces.RAGService/Retrieval',
                request_serializer=rag__pb2.RetrievalRequest.SerializeToString,
                response_deserializer=rag__pb2.RetrievalResponse.FromString,
                )
        self.CreateIndex = channel.unary_unary(
                '/raghub_interfaces.RAGService/CreateIndex',
                request_serializer=rag__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=rag__pb2.CreateIndexResponse.FromString,
                )
        self.Chat = channel.unary_stream(
                '/raghub_interfaces.RAGService/Chat',
                request_serializer=chat__pb2.CreateChatCompletionRequest.SerializeToString,
                response_deserializer=chat__pb2.CreateChatCompletionResponse.FromString,
                )
        self.AddDocuments = channel.unary_unary(
                '/raghub_interfaces.RAGService/AddDocuments',
                request_serializer=rag__pb2.AddDocumentsRequest.SerializeToString,
                response_deserializer=rag__pb2.AddDocumentsResponse.FromString,
                )
        self.DeleteDocuments = channel.unary_unary(
                '/raghub_interfaces.RAGService/DeleteDocuments',
                request_serializer=rag__pb2.DeleteDocumentsRequest.SerializeToString,
                response_deserializer=rag__pb2.DeleteDocumentsResponse.FromString,
                )


class RAGServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieval': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieval,
                    request_deserializer=rag__pb2.RetrievalRequest.FromString,
                    response_serializer=rag__pb2.RetrievalResponse.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=rag__pb2.CreateIndexRequest.FromString,
                    response_serializer=rag__pb2.CreateIndexResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=chat__pb2.CreateChatCompletionRequest.FromString,
                    response_serializer=chat__pb2.CreateChatCompletionResponse.SerializeToString,
            ),
            'AddDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocuments,
                    request_deserializer=rag__pb2.AddDocumentsRequest.FromString,
                    response_serializer=rag__pb2.AddDocumentsResponse.SerializeToString,
            ),
            'DeleteDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocuments,
                    request_deserializer=rag__pb2.DeleteDocumentsRequest.FromString,
                    response_serializer=rag__pb2.DeleteDocumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raghub_interfaces.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raghub_interfaces.RAGService/Retrieval',
            rag__pb2.RetrievalRequest.SerializeToString,
            rag__pb2.RetrievalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raghub_interfaces.RAGService/CreateIndex',
            rag__pb2.CreateIndexRequest.SerializeToString,
            rag__pb2.CreateIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/raghub_interfaces.RAGService/Chat',
            chat__pb2.CreateChatCompletionRequest.SerializeToString,
            chat__pb2.CreateChatCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raghub_interfaces.RAGService/AddDocuments',
            rag__pb2.AddDocumentsRequest.SerializeToString,
            rag__pb2.AddDocumentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raghub_interfaces.RAGService/DeleteDocuments',
            rag__pb2.DeleteDocumentsRequest.SerializeToString,
            rag__pb2.DeleteDocumentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
