[project]
name = "raghub-protos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "protobuf-pydantic-gen",
]

[tool.uv.sources]
protobuf-pydantic-gen = { git = "https://github.com/begonia-org/pydantic-protobuf-gen.git", rev = "master" }

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
