[project]
name = "raghub-interfaces"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "grpcio-tools>=1.62.3",
 "hypercorn==0.17.3",
 "protobuf-pydantic-gen>=0.1.7",
 "typer>=0.15.2",
 "raghub-core>=0.1.0",
 "raghub-ext",
 "raghub-app",
]

[tool.uv]
managed = true
[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true


[tool.uv.sources]
raghub-ext = { workspace = true }
raghub-app = { workspace = true }
raghub-core = { workspace =true }
protobuf-pydantic-gen = { git = "https://github.com/begonia-org/pydantic-protobuf-gen.git", rev = "feature/fastapi-grpc" }
[project.scripts]
raghub = 'raghub_interfaces.raghub:main'
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
